### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by ghost**
Targeting:
- Usage on Windows
- Ignoring files and folders starting with a dot (".")
- Finding interpreter from shebang on non-windows clients

### CODE REVIEW

**Comment by ghost** [comment]
I've tested this some more. On Linux/Macos it works as expected.
However, on Windows it also tries to start the script. But because of the lag of an shebang mechanism on windows many of the scripts i've tested just popping up in the default editor `notepad.exe`. If you register the file extensions correctly, it works as expected, too.

An alternative way could be to try parsing a shebang line from the script and use the windows internals to find a proper executable for it (checking file extension against envvar `%PATHEXT%`, using `where` to find executable (its like `which` on linux)).

**Comment by sirikon** [comment]
I don't think that implementing here a shebang mechanism for Windows is the correct way to deal with it.

Not sure how it works on Windows, but in Linux the shebang mechanism is built into the kernel. Trying to execute a script with permission to execute and a shebang will work, and it shouldn't be necessary calling `sh` to do so (which was my error back then, when did the implementation).

So, maybe just trying to execute the scripts, in whatever platform you're, works enough?

At the end it's your decission :)

**Comment by sirikon** [comment]
Also, I'm thinking that I don't maintain/use this project anymore, and in the case of needing one, I would make a new one in another language like Crystal or Zig.

So I'm thinking of just updating the readme with a big "NOT MAINTAINED ANYMORE" and a link to your fork. What you think?

**Comment by ghost** [comment]
Hi,
i'm ok with that, working on it anyway.
You are right, it should a better way of running the scripts. I keep that in mind, thank you for your patience.

**Comment by sirikon** [comment]
Hey @stevenkl , changed the README 4 days ago but forgot to tell you here :smile: .

**Comment by ghost** [comment]
Hi,
no problem,  I've already seen it.
Thanks for your response.

**Pull request closed without merging**
